apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.deployment.name }}
          image: {{ .Values.deployment.image }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          env:
            - name: QUARKUS_HTTP_PORT
              value: "{{ .Values.deployment.env.quarkusHttpPort }}"
          ports:
            - containerPort: {{ .Values.deployment.ports.http.containerPort }}
              name: {{ .Values.deployment.ports.http.name }}
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.probes.readiness.path }}
              port: {{ .Values.deployment.probes.readiness.port }}
            initialDelaySeconds: {{ .Values.deployment.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.deployment.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.deployment.probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.probes.liveness.path }}
              port: {{ .Values.deployment.probes.liveness.port }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
      tolerations:
        {{- toYaml .Values.deployment.tolerations | nindent 8 }}