apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
spec:
  hosts:
{{- range .Values.virtualService.hosts }}
  - {{ . | quote }}
{{- end }}
  gateways:
{{- range .Values.virtualService.gateways }}
  - {{ . | quote }}
{{- end }}
  http:
{{- range .Values.virtualService.http }}
  - match:
{{- range .match }}
    - uri:
        prefix: {{ .uri.prefix | quote }}
{{- end }}
    {{- if .rewrite }}
    rewrite:
      uri: {{ .rewrite.uri | quote }}
    {{- end }}
    route:
{{- range .route }}
    - destination:
        host: {{ .destination.host | quote }}
        port:
          number: {{ .destination.port }}
{{- end }}
{{- end }}